"""add session summary

Revision ID: 575e6a1ef4da
Revises: dbeabdf274b9
Create Date: 2026-05-13 16:32:20.106466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575e6a1ef4da'
down_revision: Union[str, Sequence[str], None] = 'dbeabdf274b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'summary')
    # ### end Alembic commands ###
