"""add langfuse_trace_id and evaluations table

Revision ID: f7306865adec
Revises: 575e6a1ef4da
Create Date: 2026-05-14 18:02:30.741604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7306865adec'
down_revision: Union[str, Sequence[str], None] = '575e6a1ef4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('score_name', sa.Text(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evaluated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_consultation_id'), 'evaluations', ['consultation_id'], unique=False)
    op.add_column('consultations', sa.Column('langfuse_trace_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'langfuse_trace_id')
    op.drop_index(op.f('ix_evaluations_consultation_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
